repos:
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: pylint tinygrad/
          language: system
          always_run: true
          pass_filenames: false
        - id: mypy
          name: mypy
          entry: mypy tinygrad/ --ignore-missing-imports
          language: system
          always_run: true
          pass_filenames: false
