# pip install mkdocs mkdocs-material mkdocstrings[python]
site_name: tinygrad docs
site_url: https://docs.tinygrad.org/
nav:
- Home: index.md
- Tensor: tensor.md
- dtypes: dtypes.md
- Neural Networks: nn.md
- MNIST Tutorial: mnist.md
- Quickstart: quickstart.md
- Showcase: showcase.md
- Developer: developer.md
- Function: function.md
- Environment: env_vars.md
#- tinygrad: reference/

#extra_css:
#- css/tinygrad.css

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.inlinehilite:
    style_plain_text: python
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- toc:
    permalink: "¤"

theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
    scheme: slate
    primary: black
    accent: lime
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        paths: [tinygrad]
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          filters: ["!^_"]
          heading_level: 3
          inherited_members: false
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_source: true
          signature_crossrefs: true
          summary: true
- markdown-exec
#- gen-files:
#    scripts:
#      - docs/gen_ref_pages.py
#- literate-nav:
#    nav_file: SUMMARY.md
