name: Benchmarks

on:
  push:
    branches:
      - master
      - update_benchmark

jobs:
  testmacbenchmark:
    name: Mac Benchmark
    runs-on: [self-hosted, macOS]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Run model inference benchmark
      run: python3 test/external/external_model_benchmark.py
    - name: Run 10 CIFAR training steps
      run: STEPS=10 python3 examples/hlb_cifar10.py
    - uses: actions/upload-artifact@v3
      with:
        name: ONNX Inference Speed (Mac)
        path: onnx_inference_speed.csv
  testamdbenchmark:
    name: AMD Benchmark
    runs-on: [self-hosted, Linux]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Run model inference benchmark
      run: python3 test/external/external_model_benchmark.py
    - name: Run 10 CIFAR training steps
      run: STEPS=10 python3 examples/hlb_cifar10.py
    - uses: actions/upload-artifact@v3
      with:
        name: ONNX Inference Speed (AMD)
        path: onnx_inference_speed.csv
