name: Unit Tests

on: [push, pull_request]

jobs:
  lines:
    name: Less than 1000 lines
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install SLOCCount
      run: sudo apt-get install sloccount
    - name: Check <1000 lines
      run: sloccount tinygrad test examples; if [ $(sloccount tinygrad | sed -n 's/.*Total Physical Source Lines of Code (SLOC)[ ]*= \([^ ]*\).*/\1/p' | tr -d ',') -gt 1000 ]; then exit 1; fi

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install OpenCL
      run: sudo apt-get install pocl-opencl-icd
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: pip install -e '.[gpu,testing]'
    - name: Run Pytest
      run: python -m pytest -s -v

  linter:
      name: Indentation Linter
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install PyLint
        run: sudo apt-get install pylint
      - name: Validate indentation is 2 lines
        run: if [[ $(pylint --jobs=0 --indent-string='  ' * | grep "Bad indentation") ]]; then exit 1; fi
